### ISSUE TITLE
Raspberry Pi OS 2022.01.28 64bit 版 setup.sh

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/chirimen#118]
[Raspberry Pi OS 2022.01.28 64bit 版](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-01-28/)
### TODO List
- [ ] フォント問題 => 32bit 方式 https://github.com/chirimen-oh/chirimen/issues/109#issuecomment-893095558
- [ ] npm, node => 32bit 方式
- [ ] vscode
  - [ ] apt-get install OK 
  - [ ] デスクトップにショートカットができていない
  - [ ] 設定に失敗している可能性あり
- [ ] arduino 
  - [ ] apt-get install OK 
  - [ ] ショートカットアイコン が複数できる => 旧セットアップを削除で解決
  - [ ] 64bit版かどうか要確認=>64bit
- [ ] ブックマーク
  - [ ] チュートリアル
  - [ ] ヘルプ
  - [ ] Top
  - [ ] Example
  - [ ] JS Bin
  - [ ] JSFiddle
  - [ ] codesandbox
  - [ ] CHIRIMEN サイト
- [ ] 壁紙
- [ ] apt の sourcelist => [修正](d3391d0)
  - ~~※暫定でsource.list指定をコメント化して問題回避中~~
- [ ] ~~apache が起動していない~~ トップページが開かない

**Comment by gurezo** [comment]
2022.09.06 番がリリースされたので、close

**Comment by gurezo** [comment]
#122 へ引き継ぎ
