### ISSUE TITLE
Raspberry Pi OS 2024-11-19 64bit 版 setup.sh

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/chirimen#122]
- [raspios_arm64-2024-11-19](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2024-11-19/)
- ref. [Raspberry Pi OSのパッケージング](https://tkyonezu.com/iot/raspberry-pi-os%E3%81%AE%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%83%B3%E3%82%B0/)

### TODO List
- [ ] フォント問題 => 32bit 方式 https://github.com/chirimen-oh/chirimen/issues/109#issuecomment-893095558
- [ ] npm, node => 32bit 方式
- [ ] vscode
  - [ ] apt-get install OK 
  - [ ] デスクトップにショートカットができていない
  - [ ] 設定に失敗している可能性あり
- [ ] arduino 
  - [ ] apt-get install OK 
  - [ ] ショートカットアイコン が複数できる => 旧セットアップを削除で解決
  - [ ] 64bit版かどうか要確認=>64bit
- [ ] ブックマーク
  - [ ] チュートリアル
  - [ ] ヘルプ
  - [ ] Top
  - [ ] Example
  - [ ] JS Bin
  - [ ] JSFiddle
  - [ ] codesandbox
  - [ ] CHIRIMEN サイト
- [ ] 壁紙
- [ ] apt の sourcelist => [修正](d3391d0)
  - ~~※暫定でsource.list指定をコメント化して問題回避中~~
- [ ] ~~apache が起動していない~~ トップページが開かない

**Comment by gurezo** [comment]
cf. https://github.com/chirimen-oh/meeting/blob/master/2025/meeting-2025.04.21.md


- Chirimen Desktop 版保留（塩漬け）
- Chirimen Desktop 版のニーズが出たら、相談する
- Chirimen Desktop 版を作り直す時に修正する
